# Then override the value of CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS
set(CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS "${CMAKE_CURRENT_LIST_FILE}/emscan-deps" CACHE FILEPATH "Custom clang-scan-deps path" FORCE)
set(CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS "${CMAKE_CURRENT_LIST_FILE}/emscan-deps")
set(CMAKE_C_COMPILER_CLANG_SCAN_DEPS "${CMAKE_CURRENT_LIST_FILE}/emscan-deps" CACHE FILEPATH "Custom clang-scan-deps path" FORCE)
set(CMAKE_C_COMPILER_CLANG_SCAN_DEPS "${CMAKE_CURRENT_LIST_FILE}/emscan-deps")
